---
#
# Downloads and installs ccache
# @requires: version=3.2.4
#

- name: "ccache : download and extract"
  unarchive:
    dest: /tmp/
    remote_src: yes
    src: "https://www.samba.org/ftp/ccache/ccache-{{ version }}.tar.gz"
  register: new_archive

- name: "ccache : prepare for compilation"
  shell: ./configure -q
    chdir: "/tmp/ccache-{{ version }}"

- name: "ccache : compile"
  make: chdir="/tmp/ccache-{{ version }}"

- name: "ccache : install"
  copy:
    dest: "{{ ccache_dest }}"
    mode: 0755
    remote_src: yes
    src: "/tmp/ccache-{{ version }}/ccache"

- name: "ccache : create symlinks"
  loop_control:
    loop_var: destination
  with_items: [ 'gcc', 'cc', 'g++', 'c++' ]
  file:
    dest: "/usr/local/bin/{{ destination }}"
    src: /usr/local/bin/ccache
    state: link

- name: "ccache : cleanup"
  file: path="/tmp/ccache-{{ version }}" state=absent
