---

#
# common tasks suitable for all machines
#

  - name: collect host info
    gather_facts: gather_subset=hardware

  - name: set hostname
    hostname: name="{{ inventory_hostname }}"

  - name: create the active user
    user: name="{{ server_user }}" shell=/bin/bash

  - name: add ::1 to /etc/hosts for ipv6 compat
    lineinfile:
      dest: /etc/hosts
      state: present
      line:  "::1 localhost.localdomain localhost"

  - name: update freebsd package source
    when: "{{ os|startswith('freebsd') }}"
    lineinfile:
      dest: /etc/pkg/FreeBSD.conf
      regex: '^(\s+)url\:'
      state: present
      line: '  url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest",'

  - name: run 'upgrade packages' playbook
    include: "../upgrade-packages.yml"
