---

#
# common tasks suitable for all machines
#

- name: gather facts
  setup: gather_subset=hardware

# setting hostname is not supported for all os'es. see
# https://github.com/ansible/ansible-modules-core/issues/4818
# https://github.com/ansible/ansible-modules-core/issues/4782
- name: set hostname
  when: not os|startswith("alpine") and not os|startswith("smartos")
  hostname: name="{{ inventory_hostname }}"

- name: create the active user
  user: name="{{ server_user }}" shell=/bin/bash

- name: add ::1 to /etc/hosts for ipv6 compat
  lineinfile:
    dest: /etc/hosts
    state: present
    line: ::1 localhost.localdomain localhost

- name: disable joyent smartconnect
  when: os|startswith("smartos")
  notify: restart sshd
  lineinfile: state=absent dest="{{ ssh_config }}" regexp=libsmartsshd.so

- name: change default coredump folder
  when: os|startswith("smartos")
  shell: coreadm -g /home/iojs/cores/core.%f.%p -e global

- name: disable sftp
  when: not os|startswith("win")
  notify: restart sshd
  lineinfile: state=absent dest="{{ ssh_config }}" regexp=^Subsystem(\s+)sftp

- include: repos.yml

- name: install packages
  package: name={{ item }} state=present
  with_items: "{{ common_packages }} + {{ packages[os|stripversion] }}"

- name: run ccache installer
  when: os in ccache_no_binpkg
  include: ccache.yml version=3.3.2

- include: ntp.yml
