---

#
# common tasks suitable for all machines
#

  - name: gather facts
    setup: gather_subset=hardware

  - name: set hostname
    # setting hostname is not supported for all os'es
    when: not os|startswith("alpine") or not os|startswith("smartos")
    hostname: name="{{ inventory_hostname }}"

  - name: create the active user
    user: name="{{ server_user }}" shell=/bin/bash

  - name: add ::1 to /etc/hosts for ipv6 compat
    lineinfile:
      dest: /etc/hosts
      state: present
      line:  "::1 localhost.localdomain localhost"

  - include: repos.yml
  - include: ntp.yml
