---

#
# fetches ccache statistics from all hosts
#

- hosts: test

  tasks:
    - name: collect ccache statistics
      script: ../partials/ccache_statistics.sh
      become: yes
      become_user: "{{ server_user }}"
