---

#
# sets up the host that runs nodejs.org, iojs.org and dist.libuv.org
#
# note: you have to account for a lot of storage in /home/dist - it is
#       currently using block storage from digitalocean which you will
#       have to set up manually and have mounted to /home/dist
#       before proceeding

- hosts: infra-digitalocean-ubuntu1604-x64-1
  roles:
    - bootstrap
    - baselayout
    - package-upgrade

  pre_tasks:
    - name: check if secrets are properly set
      fail:
      failed_when: not {{ secret }}
      loop_control:
        loop_var: secret
      with_items:
        - github_secret
        - cdn_api_key
        - cdn_api_email
        - cdn_api_iojs_id
        - cdn_api_nodejs_id
        - cloudfuse_user
        - cloudfuse_key

  tasks:
    - name: add nodesource signing key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
    - name: add nodesource repo
      apt_repository:
        repo: "{{ repo }}"
        state: present
        update_cache: yes
      loop_control:
        loop_var: repo
      with_items:
        - deb https://deb.nodesource.com/node_6.x jessie main
        - deb-src https://deb.nodesource.com/node_6.x jessie main
