---

#
# set up a jenkins worker -- muy bueno!
#

- hosts: test
  roles:
    - bootstrap
    - baselayout
    - package-upgrade
    - jenkins-worker

  pre_tasks:
    - name: check if secret is properly set
      fail:
      failed_when: not secret
