---

#
# set up a jenkins worker -- muy bueno!
#

- hosts: test
  roles:
    - bootstrap
    - baselayout
    - package-upgrade
    - jenkins-worker

  pre_tasks:
    - name: check if host_vars file exists exists
      local_action: stat path="../host_vars/{{ inventory_hostname }}"
      register: hostvar
      failed_when: "not hostvar.stat.exists"
