---

#
# Update packages
#

  - hosts: all
    vars:
      pm: {
        'apk': 'alpine',
        'yum': 'centos',
        'apt': ['debian', 'ubuntu'],
        'dnf': 'fedora',
        'pkg': 'freebsd',
        'pkgin': 'smartos',
      }
      template: "{{ os|match_key(pm, 'os') }}"

    tasks:

    - name: include os-specific package manager
      include: "../partials/packages/{{ template }}.yml"
      failed_when: template is False
