---

#
# alpine34 repos - these are required in bootstrap so they're probably in place
#

- name: add package repos
  lineinfile: dest=/etc/apk/repositories create=yes line="{{ item }}"
  with_items:
    - https://dl-3.alpinelinux.org/alpine/edge/main
    - https://dl-3.alpinelinux.org/alpine/edge/community
