---

#
# get regular instead of quarterly updates
#

- name: "repos : add package repos"
  lineinfile:
    dest: /etc/pkg/FreeBSD.conf
    regexp: '^(\s+)url\:'
    state: present
    line: '  url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest",'

# if the schema definition is updated this is required for any following
# `pkg` commands to work
- name: "repos : update definition"
  raw: pkg update -q
