---

#
# fetches jenkins and make sure it is started properly
#

- name: download slave.jar
  get_url:
  args:
    url: "{{ jenkins_worker_jar }}"
    dest: /home/{{ server_user }}/slave.jar
    mode: 0644

- name: render init script into place
  template:
  args:
    src: "{{ jenkins.src }}"
    dest: "{{ jenkins.dest }}"
    mode: "{{ jenkins.mode|default('0644') }}"

- name: enable jenkins at startup
  service: name=jenkins state=started enabled=yes

- name: install monit
  when: os in needs_monit
  include: monit.yml
